#include<iostream>
using namespace std;
main()
{
int sum;
int mul;
int subtract;
int result;
int num1;
int num2;
int num3;
int num4;
int num5;
int num6;
int num7;
int num8;
int num9;
int num10;
int num11;
int num12;
int num13;
int num14;
int num15;
cout<<"enter 1st number:";
cin>>num1;
cout<<"enter 2nd number:";
cin>>num2;
cout<<"enter 3rd number:";
cin>>num3;
cout<<"enter 4th number:";
cin>>num4;
cout<<"enter 5th number:";
cin>>num5;
cout<<"enter 6th number:";
cin>>num6;
cout<<"enter 7th number:";
cin>>num7;
cout<<"enter 8th number:";
cin>>num8;
cout<<"enter 9th number:";
cin>>num9;
cout<<"enter 10th number:";
cin>>num10;
cout<<"enter 11th number:";
cin>>num11;
cout<<"enter 12th number:";
cin>>num12;
cout<<"enter 13th number:";
cin>>num13;
cout<<"enter 14th number:";
cin>>num14;
cout<<"enter 15th number:";
cin>>num15;
sum=num1+num2+num3+num4+num5;
mul=num6*num7*num8*num9*num10;
subtract=num11-num12-num13-num14-num15;
result=(sum+mul)-subtract;
cout<<"total:"<<result;
}